research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current date is {current_month} {current_year}.
  expected_output: >
    A list with 10 most relevant news & progress on {topic} with summary, details, excerpts, and more
  agent: researcher

reporting_task:
  description: >
    Review the context you got and organize each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

scripting_task:
  description: >
    Review the report and plan, and write an elaborate podcast script between two hosts
    who are knowledgable about the topic and yet are fun on podcast
  expected_output: >
    A full script with speaker labels, sound effects, laughs, silences, and every last bit of details. Pass that to gemini voice tool to generate and save podcast. "Jone" and "Jane" are the speakers, give them dialogues by name.
  agent: scriptwriter
